baseURL = "https://marcanuy.github.io/simpleit-hugo-theme/"
languageCode = "en-us"
title = "SimpleIT Hugo theme demo website"
theme = 'simpleit-hugo-theme'
disqusShortname = "simpleit-hugo-theme"
googleAnalytics = "UA-64047109-4"
canonifyURLs = true

# Build robots.txt file
enableRobotsTXT = true
enableGitInfo = true #makes .Lastmod (on Page) to be fetched from Git

# syntax highlighting
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 10
    bio = "OSS enthusiast."
    page_about_me_relurl = "/about/"
  [languages.es]
    title = "Sitio web de ejemplo usando SimpleIT Hugo"
    contentDir = "content/es"
    languageName = "Espa√±ol"
    weight = 20
    bio = "Entusiasta OSS."
    page_about_me_relurl = "/es/acerca/"

# Theme variables
#
[params]
  # Description/subtitle for homepage (can be Markdown)
  description = "SimpleIT is a Hugo theme with mobile-first design."

  # Render Share buttons static or with javascript
  shareButtonsType = "static" #<static|javascript>

  # Format dates with Go's time formatting
  date_format = "Mon Jan 02, 2006"

  # Your copyright notice - appears in site footer.
  # To display a copyright symbol, type `&copy;`.
  copyright = "<small>&copy; 2018</small>"

  # used in page level ads in head
  #google_adsense_id = "ca-pub-1234567890"
  
  # verification string for Google Webmaster Tools
  #google_verify_meta = "1234567890"

  # verification string for Bing Webmaster Tools
  #bing_verify_meta = "1234567890"

  # verification string for Yandex Webmaster Tools
  #yandex_verify_meta = "1234568790"

  # site handler
  twitter = "marcanuy"

  # Buymeacoffe id (https://buymeacoffee.com)
  buymeacoffe = "marcanuy"

  [params.author]
  name = "Marcelo Canina"
  country = "Uruguay"
  twitter = 'marcanuy'
  website = 'https://marcanuy.com'
  gravatar = "2ebdffd5ddb4a98b0cc77117503d2711"
  linkedin = "marcelocanina"
  mail = "me@marcanuy.com"
  github = "marcanuy"
  gitlab = "marcanuy"
  stackexchange = "1193189"


